#!/bin/bash

# This script is intended to be run from the project root directory.

num_uncommited=$(git status --porcelain 2>/dev/null | wc -l)

if [[ $num_uncommited -ne 0 ]]; then
  echo "There are uncommitted changes. Test them and commit them before publishing."
  exit 1
fi

# Generate the site into _site
jekyll build

# Copy the generated site content to a temp folder
TMPSITE=`mktemp -d /tmp/jekyll-cyph.XXXX`
cp -r _site/* $TMPSITE/

# Checkout the "master" branch
git checkout master

# Copy the produced files from the temp directory up to the top level
cp -r $TMPSITE/* ./

# Stage all the new files and changes
git add --all

# Commit the stage new files and changes
git commit -m "Publishing pure static site."

# Push the master branch up to origin
git push origin master:master

# Checkout the "jekyll-site-src" branch
git checkout jekyll-site-src
