#!/bin/bash

# This script is intended to be run from the project root directory.

num_uncommited=$(git status --porcelain 2>/dev/null | wc -l)

if [[ $num_uncommited -ne 0 ]]; then
  echo "There are uncommitted changes. Test them and commit them before publishing."
  exit 1
fi

# Generate the site into _site
jekyll

# Checkout the "master" branch
git checkout master

# Move the produced files in the _site directory up to the top level

# Remove the _site directory

# Stage all the new files and changes

# Commit the stage new files and changes

# Push the master branch up to origin

# Checkout the "jekyll-site-src" branch
